// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk0DUwkHIGGa3L3XdHaSO56fRBI4T0A_w',
    appId: '1:375032533675:web:32a5046db89e67a6e79dee',
    messagingSenderId: '375032533675',
    projectId: 'real-time-chat-app-2b629',
    authDomain: 'real-time-chat-app-2b629.firebaseapp.com',
    storageBucket: 'real-time-chat-app-2b629.appspot.com',
    measurementId: 'G-TNVQT16CS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqd0oXku0xpQyuYkSphdgPZi3tIP1VPks',
    appId: '1:375032533675:android:ae3dfb14c0c26dc5e79dee',
    messagingSenderId: '375032533675',
    projectId: 'real-time-chat-app-2b629',
    storageBucket: 'real-time-chat-app-2b629.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs_yClSmG65mur_iNBOOIbYZ51JY_KLzY',
    appId: '1:375032533675:ios:cc5f34cb418a5e58e79dee',
    messagingSenderId: '375032533675',
    projectId: 'real-time-chat-app-2b629',
    storageBucket: 'real-time-chat-app-2b629.appspot.com',
    iosBundleId: 'com.example.realTimeChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs_yClSmG65mur_iNBOOIbYZ51JY_KLzY',
    appId: '1:375032533675:ios:cc5f34cb418a5e58e79dee',
    messagingSenderId: '375032533675',
    projectId: 'real-time-chat-app-2b629',
    storageBucket: 'real-time-chat-app-2b629.appspot.com',
    iosBundleId: 'com.example.realTimeChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk0DUwkHIGGa3L3XdHaSO56fRBI4T0A_w',
    appId: '1:375032533675:web:e2d70337c39aa7c7e79dee',
    messagingSenderId: '375032533675',
    projectId: 'real-time-chat-app-2b629',
    authDomain: 'real-time-chat-app-2b629.firebaseapp.com',
    storageBucket: 'real-time-chat-app-2b629.appspot.com',
    measurementId: 'G-Z12XRY8H9N',
  );
}
